# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GAMMA": "00_core.ipynb",
         "NYSAPI": "00_core.ipynb",
         "NEW_YORK_EVENTS": "00_core.ipynb",
         "plot_data_and_fit": "00_core.ipynb",
         "FirstInChunkSelector": "01_lasso.ipynb",
         "LassoICSelector": "01_lasso.ipynb"}

modules = ["core.py",
           "lasso.py"]

doc_url = "https://ababino.github.io/babino2020masks/"

git_url = "https://github.com/ababino/babino2020masks/tree/master/"

def custom_doc_links(name): return None
