# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NYSAPI": "00_core.ipynb",
         "NEW_YORK_EVENTS": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ababino.github.io/babino2020masks/"

git_url = "https://github.com/ababino/babino2020masks/tree/master/"

def custom_doc_links(name): return None
